let quarterbackName = "Kelvin Remmard";
let runningBackName = "Evante Simons";
let wideReceiverName = "Aaron Flynn";
let tightEndName = "Drew Cobb";
let oLinemanName = "Malcolm Curtis";
let dLinemanName = "Darren Patterson";
let linebackerName = "Moe Young";
let defensiveBackName = "Malik Malachi";
let teamName = "Scorpions";
let QBtoTEtd = `${quarterbackName} finds ${tightEndName} in the endzone for a ${teamName} touchdown!`;
console.log(QBtoTEtd);
